-- MySQL Script generated by MySQL Workbench
-- Wed Jul 13 14:38:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Taxis
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Taxis` ;

-- -----------------------------------------------------
-- Schema Taxis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Taxis` DEFAULT CHARACTER SET utf8 ;
USE `Taxis` ;

-- -----------------------------------------------------
-- Table `Taxis`.`Vendor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Taxis`.`Vendor` ;

CREATE TABLE IF NOT EXISTS `Taxis`.`Vendor` (
  `Id_Vendor` INT NOT NULL,
  `Vendor_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Vendor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Taxis`.`Rate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Taxis`.`Rate` ;

CREATE TABLE IF NOT EXISTS `Taxis`.`Rate` (
  `Id_Rate` INT NOT NULL,
  `Rate_Code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Rate`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Taxis`.`Pay_Tipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Taxis`.`Pay_Tipe` ;

CREATE TABLE IF NOT EXISTS `Taxis`.`Pay_Tipe` (
  `Id_Pay_Tipe` INT NOT NULL AUTO_INCREMENT,
  `Pay_Tipe_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Pay_Tipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Taxis`.`Calendario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Taxis`.`Calendario` ;

CREATE TABLE IF NOT EXISTS `Taxis`.`Calendario` (
  `Fecha` DATETIME NOT NULL,
  `Año` INT NOT NULL,
  `Dia` INT NOT NULL,
  `Mes` INT NOT NULL,
  `Semana` INT NOT NULL,
  `Trimestre` INT NOT NULL,
  `Mitad_Año` INT NOT NULL,
  `Dia_Semana` INT NOT NULL,
  PRIMARY KEY (`Fecha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Taxis`.`Borough`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Taxis`.`Borough` ;

CREATE TABLE IF NOT EXISTS `Taxis`.`Borough` (
  `Id_Borough` INT NOT NULL AUTO_INCREMENT,
  `Borough` VARCHAR(45) NOT NULL,
  `Latitud` DECIMAL(11,10) NOT NULL,
  `Longitud` DECIMAL(11,10) NOT NULL,
  PRIMARY KEY (`Id_Borough`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Taxis`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Taxis`.`Location` ;

CREATE TABLE IF NOT EXISTS `Taxis`.`Location` (
  `Id_Location` INT NOT NULL AUTO_INCREMENT,
  `Zone_Name` VARCHAR(45) NOT NULL,
  `Id_Borough` INT NOT NULL,
  `Locationcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Location`),
  INDEX `Borough_idx` (`Id_Borough` ASC) VISIBLE,
  CONSTRAINT `Borough`
    FOREIGN KEY (`Id_Borough`)
    REFERENCES `Taxis`.`Borough` (`Id_Borough`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Taxis`.`Trip_Data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Taxis`.`Trip_Data` ;

CREATE TABLE IF NOT EXISTS `Taxis`.`Trip_Data` (
  `Id_Trip_Data` INT NOT NULL AUTO_INCREMENT,
  `Id_Vendor` INT NOT NULL,
  `Pickup_DateTime` DATETIME NOT NULL,
  `Dropoff_DateTime` DATETIME NOT NULL,
  `Passager_Count` INT NOT NULL,
  `Trip_Distance` DOUBLE NOT NULL,
  `Id_Rate_Code` INT NOT NULL,
  `Store_Fwd_Flag` Varchar(4)NOT NULL,
  `PU_Location` INT NOT NULL,
  `DO_Location` INT NOT NULL,
  `Id_Pay_Type` INT NOT NULL,
  `Fare_Amount` DOUBLE NOT NULL,
  `Extra` DOUBLE NOT NULL,
  `Mta_Tax` DOUBLE NOT NULL,
  `Tip_Amount` DOUBLE NOT NULL,
  `Tolls_Amount` DOUBLE NOT NULL,
  `Improve_Surcharge` DOUBLE NOT NULL,
  `Total_Amount` DOUBLE NOT NULL,
  `Congestion_Surcharge` DOUBLE NOT NULL,
  `Tiempo_Viaje` DECIMAL(15,7) NOT NULL,
  PRIMARY KEY (`Id_Trip_Data`),
  INDEX `Vendor_idx` (`Id_Vendor` ASC) VISIBLE,
  INDEX `Rate_idx` (`Id_Rate_Code` ASC) VISIBLE,
  INDEX `Pay_Tipe_idx` (`Id_Pay_Type` ASC) VISIBLE,
  INDEX `Pick_up_idx` (`Pickup_DateTime` ASC) VISIBLE,
  INDEX `Drop_off_idx` (`Dropoff_DateTime` ASC) VISIBLE,
  INDEX `PU_idx` (`PU_Location` ASC) VISIBLE,
  INDEX `DO_idx` (`DO_Location` ASC) VISIBLE,
  CONSTRAINT `Vendor`
    FOREIGN KEY (`Id_Vendor`)
    REFERENCES `Taxis`.`Vendor` (`Id_Vendor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Rate`
    FOREIGN KEY (`Id_Rate_Code`)
    REFERENCES `Taxis`.`Rate` (`Id_Rate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Pay_Tipe`
    FOREIGN KEY (`Id_Pay_Type`)
    REFERENCES `Taxis`.`Pay_Tipe` (`Id_Pay_Tipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Pick_up`
    FOREIGN KEY (`Pickup_DateTime`)
    REFERENCES `Taxis`.`Calendario` (`Fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Drop_off`
    FOREIGN KEY (`Dropoff_DateTime`)
    REFERENCES `Taxis`.`Calendario` (`Fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PU`
    FOREIGN KEY (`PU_Location`)
    REFERENCES `Taxis`.`Location` (`Id_Location`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DO`
    FOREIGN KEY (`DO_Location`)
    REFERENCES `Taxis`.`Location` (`Id_Location`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Taxis`.`Weather`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Taxis`.`Weather` ;

CREATE TABLE IF NOT EXISTS `Taxis`.`Weather` (
  `Id_Weather` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NOT NULL,
  `Weathercol` VARCHAR(45) NOT NULL,
  `Id_Borough` INT NOT NULL,
  `Temp` DOUBLE NOT NULL,
  `Condicion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Weather`),
  INDEX `Calendario_idx` (`Fecha` ASC) VISIBLE,
  INDEX `Bourgh_idx` (`Id_Borough` ASC) VISIBLE,
  CONSTRAINT `Calendario`
    FOREIGN KEY (`Fecha`)
    REFERENCES `Taxis`.`Calendario` (`Fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Bourgh`
    FOREIGN KEY (`Id_Borough`)
    REFERENCES `Taxis`.`Borough` (`Id_Borough`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


